///
/// Code generated by @404shades https://github.com/404shades/jsonToDartModel/
///
const String _jsonKeyGetAllCoinsDataRequestDTOMethod = 'method';
const String _jsonKeyGetAllCoinsDataRequestDTOParams = 'params';
const String _jsonKeyGetAllCoinsDataRequestDTOCid = 'cid';
class GetAllCoinsDataRequestDTO {
/*
{
  "method": "SUBSCRIBE",
  "params": [
    "all@ticker"
  ],
  "cid": 1
} 
*/

  String? method;
  List<String?>? params;
  int? cid;

  GetAllCoinsDataRequestDTO({
    this.method,
    this.params,
    this.cid,
  });
  GetAllCoinsDataRequestDTO.fromJson(Map<String, dynamic> json) {
    method = json[_jsonKeyGetAllCoinsDataRequestDTOMethod]?.toString();
  if (json[_jsonKeyGetAllCoinsDataRequestDTOParams] != null && (json[_jsonKeyGetAllCoinsDataRequestDTOParams] is List)) {
  final v = json[_jsonKeyGetAllCoinsDataRequestDTOParams];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    params = arr0;
    }
    cid = int.tryParse(json[_jsonKeyGetAllCoinsDataRequestDTOCid]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (method != null) {
      data[_jsonKeyGetAllCoinsDataRequestDTOMethod] = method;
    }
    if (params != null) {
      final v = params;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data[_jsonKeyGetAllCoinsDataRequestDTOParams] = arr0;
    }
    if (cid != null) {
      data[_jsonKeyGetAllCoinsDataRequestDTOCid] = cid;
    }
    return data;
  }
}
